Feature/uppsf 3486 migrate to msk
Financial-Times/generic-rw-s3 pull request #49
Opened 2022-08-31 16:12 UTC by elenasuteva

# Description

## What

Part of the MSK migration.
Kafka v3 library updated
Logger v2 updated.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-3486

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-09-07 06:43 UTC, dtvalk-ov requested changes

2022-09-07 06:43 UTC, dtvalk-ov commented on service/handlers.go
> +		c.log.Errorf("Got error running S3 health check, %v", err.Error())
Let's use .WithError(err) and remove the formatting. There are several similar cases in processor.go as well

2022-09-07 06:43 UTC, dtvalk-ov commented on helm/generic-rw-s3/app-configs/generic-rw-s3_eks_delivery.yaml
>      value: generic-rw-s3-ConceptSuggestions
Let's use only **generic-rw-s3** in order to be consistent with the other migrated services

2022-09-07 11:36 UTC, dtvalk-ov requested changes
Sorry that I missed this in the previous review, but we need to include the kafka checks in the healthcheck/gtg.
Suggestion: As the healthcheck config is currently in handlers.go, we could create a separate healthcheck.go and a test file for better structuring.

2022-09-12 07:07 UTC, atanasdinov commented on main.go
> +		return
We can remove this.

2022-09-12 07:07 UTC, atanasdinov commented on main.go
> -	logger.Infof("Application started with args %s", os.Args)
We're losing this successful startup log.

2022-09-12 07:07 UTC, atanasdinov commented on main.go
> +	var consumer *kafka.Consumer
This definition can be skipped.

2022-09-12 07:07 UTC, atanasdinov commented on main.go
> +	qp := service.NewQProcessor(w, log)
Can be moved to the `if readTopic != nil` check below since it's not used anywhere else.

2022-09-14 11:34 UTC, elenasuteva commented on main.go
> +	var consumer *kafka.Consumer
I got this one back because I need it for the healthcheck now

2022-09-14 12:38 UTC, elenasuteva commented on helm/generic-rw-s3/app-configs/generic-rw-s3_eks_delivery.yaml
> +    value: "{{ .Values.env.KAFKA_LAG_TOLERANCE }}"
I think I fixed it now, ignore my previous comment :)

2022-09-14 14:32 UTC, dtvalk-ov approved these changes

2022-09-14 16:12 UTC, atanasdinov approved these changes
Latest changes aren't tested in neither of our environments. Approving because everything "looks" fine but please make sure to properly test it before merging.

2022-09-19 07:37 UTC, dtvalk-ov commented on service/healthcheck.go
> +	if !reflect.ValueOf(h.consumer).IsNil() {
**non-blocking question**: is there a specific reason to use reflection for nil checks, instead of a simple 
_if h.consumer != nil_ ?

2022-09-19 08:01 UTC, elenasuteva commented on service/healthcheck.go
> +	if !reflect.ValueOf(h.consumer).IsNil() {
The reason why reflection is used here is because the consumer is an interface in the healthcheck and in the healthcheck initialization we are sending the *kafka.Consumer

2022-09-19 08:02 UTC, atanasdinov approved these changes

2022-09-19 08:03 UTC, dtvalk-ov approved these changes

2022-09-19 08:09 UTC, merged